"""updated media tables

Revision ID: 119699048051
Revises: f17870ffa766
Create Date: 2025-01-07 21:16:48.701574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119699048051'
down_revision: Union[str, None] = 'f17870ffa766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audios_filename', table_name='audios')
    op.create_index(op.f('ix_audios_filename'), 'audios', ['filename'], unique=False)
    op.drop_index('ix_image_filename', table_name='image')
    op.create_index(op.f('ix_image_filename'), 'image', ['filename'], unique=False)
    op.drop_index('ix_videos_filename', table_name='videos')
    op.create_index(op.f('ix_videos_filename'), 'videos', ['filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_filename'), table_name='videos')
    op.create_index('ix_videos_filename', 'videos', ['filename'], unique=True)
    op.drop_index(op.f('ix_image_filename'), table_name='image')
    op.create_index('ix_image_filename', 'image', ['filename'], unique=True)
    op.drop_index(op.f('ix_audios_filename'), table_name='audios')
    op.create_index('ix_audios_filename', 'audios', ['filename'], unique=True)
    # ### end Alembic commands ###
